// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4sM_SzRVx2jaGCgKXQ7v9eVe0Hl-I5g',
    appId: '1:639293398436:web:ed03476893440eaf857531',
    messagingSenderId: '639293398436',
    projectId: 'nutrimotion-3a38c',
    authDomain: 'nutrimotion-3a38c.firebaseapp.com',
    storageBucket: 'nutrimotion-3a38c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9Xsrs76jue7TdzG17jgpbBcjH2aqS4c',
    appId: '1:639293398436:android:dbde33636c463e08857531',
    messagingSenderId: '639293398436',
    projectId: 'nutrimotion-3a38c',
    storageBucket: 'nutrimotion-3a38c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrghkUexPs5v0gKkzJU7VUwkKEZh2dKuk',
    appId: '1:639293398436:ios:d67a4723cb146d7b857531',
    messagingSenderId: '639293398436',
    projectId: 'nutrimotion-3a38c',
    storageBucket: 'nutrimotion-3a38c.firebasestorage.app',
    iosBundleId: 'com.example.nutrimotion',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrghkUexPs5v0gKkzJU7VUwkKEZh2dKuk',
    appId: '1:639293398436:ios:d67a4723cb146d7b857531',
    messagingSenderId: '639293398436',
    projectId: 'nutrimotion-3a38c',
    storageBucket: 'nutrimotion-3a38c.firebasestorage.app',
    iosBundleId: 'com.example.nutrimotion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg4sM_SzRVx2jaGCgKXQ7v9eVe0Hl-I5g',
    appId: '1:639293398436:web:3a08dba4d572bfa2857531',
    messagingSenderId: '639293398436',
    projectId: 'nutrimotion-3a38c',
    authDomain: 'nutrimotion-3a38c.firebaseapp.com',
    storageBucket: 'nutrimotion-3a38c.firebasestorage.app',
  );
}
