class ExerciseList {
  static final Map<String, List<String>> exercisesByGroup = {
    "Pecho": [
      "Press de banca con barra",
      "Press inclinado con mancuernas",
      "Press declinado con barra",
      "Press en máquina Smith",
      "Aperturas con mancuernas en banco plano",
      "Aperturas en banco inclinado",
      "Peck deck (contractora)",
      "Cruces en polea alta",
      "Fondos en paralelas (inclinados hacia adelante)",
      "Push-ups con peso",
    ],
    "Espalda": [
      "Dominadas (pull-ups o chin-ups)",
      "Remo con barra",
      "Remo con mancuerna",
      "Remo en máquina Hammer",
      "Remo en polea baja",
      "Jalón al pecho con agarre amplio",
      "Jalón tras nuca",
      "Peso muerto convencional",
      "Peso muerto rumano",
      "Pull-over en polea",
    ],
    "Piernas": [
      "Sentadilla con barra (back squat)",
      "Sentadilla frontal",
      "Sentadilla en Smith",
      "Prensa inclinada",
      "Zancadas caminando con mancuernas",
      "Step-up al cajón",
      "Peso muerto rumano (femorales)",
      "Curl femoral en máquina",
      "Extensiones de cuádriceps en máquina",
      "Elevaciones de talones (gemelos)",
    ],
    "Hombros": [
      "Press militar con barra",
      "Press militar con mancuernas",
      "Press Arnold",
      "Press tras nuca",
      "Elevaciones laterales con mancuernas",
      "Elevaciones frontales",
      "Pájaros (elevaciones posteriores)",
      "Remo al mentón con barra",
      "Face pulls en polea",
      "Encogimientos con mancuernas (trapecios)",
    ],
    "Bíceps": [
      "Curl con barra recta",
      "Curl con barra Z",
      "Curl con mancuernas alterno",
      "Curl martillo",
      "Curl concentrado",
      "Curl en banco Scott",
      "Curl en polea baja con barra recta",
      "Curl en polea con cuerda",
      "Curl en predicador con máquina",
      "Curl tipo spider",
    ],
    "Tríceps": [
      "Fondos en paralelas",
      "Press cerrado con barra",
      "Extensión con mancuerna tras nuca",
      "Extensión en polea con barra recta",
      "Extensión en polea con cuerda",
      "Press francés con barra Z",
      "Press francés con mancuernas",
      "Kickbacks con mancuernas",
      "Extensión en máquina de tríceps",
      "Skull crushers con barra",
    ],

    "Brazos": [
      "Curl con barra recta",
      "Curl con barra Z",
      "Curl con mancuernas alterno",
      "Curl martillo",
      "Curl concentrado",
      "Fondos en paralelas",
      "Press cerrado con barra",
      "Extensión con mancuerna tras nuca",
      "Extensión en polea con barra recta",
      "Extensión en polea con cuerda",
      "Press francés con barra Z",
    ],

    "FullBody": [
      "Sentadilla con barra (back squat)",
      "Prensa inclinada",
      "Peso muerto convencional",
      "Press de banca con barra",
      "Press inclinado con mancuernas",
      "Dominadas (pull-ups o chin-ups)",
      "Remo con barra",
      "Press militar con barra",
      "Fondos en paralelas",
      "Zancadas caminando con mancuernas",
    ],
  };
}
